name: yaffet
description: A new Flutter project.

publish_to: 'none'  


version: 1.0.0+1


environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^5.0.0
  syncfusion_flutter_charts: ^21.2.8
  conditional_builder_null_safety: ^0.0.6
  intl: ^0.18.1
  http: ^1.0.0
  sqflite: ^2.2.2
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  dio: ^5.1.2
  chart_sparkline: ^1.0.13
  getwidget: ^3.1.1
  text_scroll: ^0.2.0
  auto_animated: ^3.2.0
  auto_size_text_field: ^2.2.1
  country_icons: ^2.0.2
  flutter_screenutil: ^5.8.4
  fl_chart: ^0.63.0


dev_dependencies:
  flutter_test:
    sdk: flutter  


  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    # - images/a_dot_ham.jpeg


#  example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
#